### ISSUE TITLE
选择器建议支持正则表达式

### ISSUE THREAD

**Issue by jk2K** [waylybaye/docs.wuxiang.io#2]
目前的 CSS 选择器功能有点弱，在处理某些网页时不太方便，比如 http://m.newsmth.net/article/RealEstate/7153410， 获取作者就不太方便

**Comment by waylybaye** [comment]
这个可以用高级的选择器实现吧

**Comment by jk2K** [comment]
目前可以用 nth-child 来一个个选择，

已经完成了一个页面的规则添加，发现了以下问题

- 使用后感觉组件的效果还是太少了，比如获取帖子的正文和评论，样式上无法区分开
- 匹配到一组元素，想要排除前几个匹配项，不太方便处理，这个问题也许是我 CSS 语法还不是很熟悉
